# Generated by Django 3.2 on 2023-05-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
