# Generated by Django 3.2 on 2023-05-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_react_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='createdAt',
            new_name='createdat',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='interestedIn',
            new_name='interestedin',
        ),
    ]
